interface PrintNoteProps {
  title: string;
  reference: string;
  formula: string;
  inputs: { label: string; value: string; unit: string }[];
  result: { label: string; value: string; unit: string };
  disclaimer: string;
}

export default function PrintNote({
  title,
  reference,
  formula,
  inputs,
  result,
  disclaimer,
}: PrintNoteProps) {
  return (
    <div className="hidden print:block p-8">
      <h1 className="text-xl font-bold mb-1">{title}</h1>
      <p className="text-sm text-stone-500 mb-4">Reference: {reference}</p>
      <p className="font-mono text-lg mb-4">{formula}</p>

      <table className="w-full text-sm mb-4 border-collapse">
        <thead>
          <tr className="border-b">
            <th className="text-left py-1">Parameter</th>
            <th className="text-right py-1">Value</th>
            <th className="text-left py-1 pl-2">Unit</th>
          </tr>
        </thead>
        <tbody>
          {inputs.map((inp) => (
            <tr key={inp.label} className="border-b border-stone-200">
              <td className="py-1">{inp.label}</td>
              <td className="text-right py-1">{inp.value}</td>
              <td className="py-1 pl-2">{inp.unit}</td>
            </tr>
          ))}
          <tr className="font-bold">
            <td className="py-1">{result.label}</td>
            <td className="text-right py-1">{result.value}</td>
            <td className="py-1 pl-2">{result.unit}</td>
          </tr>
        </tbody>
      </table>

      <p className="text-xs text-stone-500 mt-6">{disclaimer}</p>
      <p className="text-xs text-stone-400 mt-2">
        Generated by CivilCalc Malaysia — {new Date().toLocaleDateString()}
      </p>
    </div>
  );
}
